### ISSUE TITLE
发现了一个错别字

### ISSUE THREAD

**Issue by BYTX-zyh** [wsdjeg/Learn-Vim_zh_cn#20]
在ch05_moving_in_file.md文件中，
位置标记下有一段 全局标签有一个好处就是，即使你在不同的项目**红**，你也可以跳转到任何一个全局标签上，全局标签可以帮助你在文件间切换。
 应当是 位置标记下有一段 全局标签有一个好处就是，即使你在不同的项目**中**，你也可以跳转到任何一个全局标签上，全局标签可以帮助你在文件间切换。

**Comment by bianyukun1213** [comment]
这一章下面

> “不断地重复这10个移动**知道**形成肌肉记忆，这花不了多少时间”

中的“知道”也应该改为“直到”。
