### ISSUE TITLE
第九章宏命令中的表述错误

### ISSUE THREAD

**Issue by sslcheese** [wsdjeg/Learn-Vim_zh_cn#38]
在“修改一个已知宏”段落，
原文为
“这里有一个问题，Vim 不能理解 <esc>。您不能依葫芦画瓢输入""，所以你需要将<Esc>写成内部代码的形式。在插入模式，在按下<esc>后按下 Ctrl-v，Vim 会打印 ^[。 Ctrl-v 是一个插入模式的操作符，可以逐字地插入一个非数字字符。你的宏命令应该如下:”

其中，“在按下< esc >后按下 Ctrl-v，Vim 会打印 ^[”，经过实测，应为“在按下Ctrl-v后按下< esc >，Vim 会打印 ^[”

**Comment by DuGangfeng** [comment]
Yes, you are right.
