### ISSUE TITLE
为什么放弃 github 转到 gitlab，不能二者共存吗

### ISSUE THREAD

**Issue by jiechen257** [wsdjeg/Learn-Vim_zh_cn#52]
如题。github是有什么限制吗？

**Comment by jiechen257** [comment]
我从 gitlab 上克隆了一份到 github 上，如果存在侵权行为请指出，我自会删除

**Comment by wsdjeg** [comment]
因为github开启了两步验证，无法登陆账号了，很多所以只能放弃了github.
