### ISSUE TITLE
区分大小写的查找

### ISSUE THREAD

**Issue by JefferyJu** [wsdjeg/Learn-Vim_zh_cn#6]
刚开始学习, 英文看的头疼, 中文版真好, 不过有一处笔误,  希望可以更正一下

> 有一个缺点。 如果只需要搜索小写字符串怎么办？ 当您执行/hello时，Vim将始终匹配其大写变体。 如果您不想匹配它们怎么办？ 您可以在搜索词前使用\c模式来告诉Vim，后续搜索词将区分大小写。 如果执行/\chello，它将严格匹配"hello"，而不是"HELLO"或"Hello"。

 '\c'模式应该是 `\C` 模式

- c  : 不区分大小写匹配
- C : 区分大小写匹配

**Comment by wsdjeg** [comment]
好的，感谢，此外，Vim 有几个选项影响到这个搜索结果，ignorecase smartcase 等等
在 2020年9月21日 09:34，Jeffery <notifications@github.com>写道：

刚开始学习, 英文看的头疼, 中文版真好, 不过有一处笔误, 希望可以更正一下

有一个缺点。 如果只需要搜索小写字符串怎么办？ 当您执行/hello时，Vim将始终匹配其大写变体。 如果您不想匹配它们怎么办？ 您可以在搜索词前使用\c模式来告诉Vim，后续搜索词将区分大小写。 如果执行/\chello，它将严格匹配"hello"，而不是"HELLO"或"Hello"。

'\c'模式应该是 \C 模式

  *   c : 不区分大小写匹配
  *   C : 区分大小写匹配

―
